version: '3.11'

services:
  api:
    build:
      context: .
    ports:
      - "${SERVICE_PORT}:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - api
      - db
    command: ["sh", "-c", "pytest --cov=api --cov-report=html:/coverage_html_report"]
    volumes:
      - ./tests:/app/tests
      - ./coverage:/app/coverage

volumes:
  db_data: